# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # ssh properties
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    # These numbers gave great performance on laptop with
    # 16 GB memory
    # quad core i7-4710HQ
    vb.memory = "4096"
    vb.cpus = "4"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end
